apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-persistent-claim-pradeep
  namespace: pradeep
spec:
  volumeMode: Filesystem
  storageClassName: pv-pradeep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
