kind: PersistentVolume
apiVersion: v1
metadata:
  name: log-persistent-volume-pradeep
  namespace: pradeep
  labels:
    type: local
spec:
  volumeMode: Filesystem
  storageClassName: pv-pradeep
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/logs-pradeep"
