apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-pradeep
  namespace: pradeep
spec:
  storageClassName: mysql-pradeep
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
