kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-volume-pradeep
  namespace: pradeep
  labels:
    type: local
spec:
  storageClassName: mysql-pradeep
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data-pradeep"
